export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
    RESET: "RESET",
    USER_DATA_UPDATE_BIO: "USER_DATA_UPDATE_BIO",
    USER_TOKEN_UPDATE: "USER_TOKEN_UPDATE",
    DATA_FETCHED_BLOG: "DATA_FETCHED_BLOG",
    UPDATE_BLOG: "UPDATE_BLOG",
  },

  blog: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    DATA_EDITED: "POST_DATA_EDITED",
    DATA_LOAD_MORE: "DATA_LOAD_MORE",
    DATA_RESET: "DATA_RESET",
    IS_LAST_PAGE: "IS_LAST_PAGE",
    BLOG_DELETE: "BLOG_DELETE",
    UPDATE_BLOG: "UPDATE_BLOG",
  },
};
